name: Run CUcumber Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup chrome
        uses: browser-actions/setup-chrome@v1.7.3

      - name: setup gradlew
        run: chmod +x gradlew

      - name: Run Cucumber Tests
        run: ./gradlew test

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: build/reports/tests/test/index.html

      - name: Upload JSON Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-json-report
          path: target/report.json